### ISSUE TITLE
Create a Pause mode

### ISSUE THREAD

**Issue by carpuplay** [carpuplay/Snake#25]
We will make a pause, we think that we can make a new state like gamepause().

**Comment by Oriol20051** [comment]
To create the pause mode we had to first create a game_pause variable, for this to work we had to make when the pause was triggered the clock tick to be 0 so that the game would stop, then we made a display fill black so that it would only be seen a black screen and finally a udapte display so that everything went correctly. To assign the pause key we use the same method as for the movement of the snake, the letter P was chosen. Finally we created a message that told you that you were paused, and if you pressed the key again you had a 3 second counter so you could prepare.
