### ISSUE TITLE
Apples are not eaten after framerate.

### ISSUE THREAD

**Issue by carpuplay** [carpuplay/Snake#29]
After changing the framerate, apples are not eaten, we belive that this error is due to the changement of the rate of moovement of the snake.

**Comment by Oriol20051** [comment]
Here the problem was that when changing the framerate the snake stopped eating the apples because the artificial grill that we created disappeared, to fix this we made the snake eat the apple when it got close enough to it, that is to say that we did it with courage absolute. In this way we were able to adjust the framerate to our liking to make it more pleasing to the eye.
![image](https://user-images.githubusercontent.com/106106675/169907811-ce84a333-8c60-4a0f-89b3-fc57b4c6c96f.png)
